name: Spawn
main: joren.spawn.Spawn
version: 0.2
description: Spawn any entity; do maniacal things with them
commands:
  spawn:
    description:
    usage:
  sp:
    description:
    usage:
  s:
    description:
    usage:
  spawn-admin:
    description:
    usage:
  sp-admin:
    description:
    usage:
  s-admin:
    description:
    usage:
  