name: Spawn
main: joren.spawn.Spawn
version: 0.2.7
description: Spawn any entity; do maniacal things with them
commands:
  ent:
    aliases: [spawn, sp, s, spawn-entity, se]
    description:
    usage:
  ent-admin:
    aliases: [spawn-admin, sp-admin, s-admin, spawn-entity-admin, se-admin]
    description:
    usage:  